###

GET http://localhost:3000/database/getUsers

###

POST http://localhost:3000/database/addUser
Content-Type: application/json

{
    "username" : "michael",
    "password" : "password123"
}

###

POST http://localhost:3000/database/createAccount
Content-Type: application/json
###

POST http://localhost:3000/database/verifyUser
Content-Type: application/json

{
    "username": "benson",
    "password": "password123"
}

###

POST http://localhost:3000/database/changePassword
Content-Type: application/json

{
    "username": "benson",
    "password": "test"
}

###

POST http://localhost:3000/database/changeEmail
Content-Type: application/json

{
    "username" : "benson",
    "newEmail" : "notBenson"
}

###

POST http://localhost:3000/database/createRoom
Content-Type: application/json

{
    "bulb" : "Hue",
    "effect" : "fade",
    "colour" : "#54a3e8"
}